resources:
  schemas:

    bronze_conglomerate_energy:
      name: ${var.prod_conglomerate_bronze_schema}
      catalog_name: ${var.catalog}
    
    silver_conglomerate_energy:
      name: ${var.prod_conglomerate_silver_schema}
      catalog_name: ${var.catalog}

    bronze_renewable_energy_chile:
      name: ${var.prod_renewable_bronze_schema}
      catalog_name: ${var.catalog}

    silver_renewable_energy_chile:
      name: ${var.prod_renewable_silver_schema}
      catalog_name: ${var.catalog}

    gold_renewable_energy_chile:
      name: ${var.prod_renewable_gold_schema}
      catalog_name: ${var.catalog}

