name: Databricks CI/CD

on:
  workflow_dispatch:
jobs:
  databricks_CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: validate Databricks CLI
        run: databricks version
      - name: Databricks Login
        run: printf '${{ secrets.DATABRICK_ACCESS_TOKEN }}' | databricks configure --host ${{ secrets.DATABRICKS_HOST }}
      - name: Validate Databricks Bundle
        run: databricks bundle validate -t dev
      - name: Deploy Databricks
        run: databricks bundle deploy -t dev
